<?php
/**
 * Pakistan-based Contract Initialization Script
 * Run this once to add a professional Pakistan contract to the database
 */

// Database configuration
$host = 'localhost';
$db = 'inventory_system';
$user = 'root';
$password = '';

try {
    $conn = new mysqli($host, $user, $password, $db);

    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }

    // Check if contract already exists
    $checkSql = "SELECT id FROM system_contracts WHERE contract_number = 'PAK-001' LIMIT 1";
    $result = $conn->query($checkSql);

    if ($result->num_rows > 0) {
        echo "<div style='background-color: #fff3cd; color: #856404; padding: 15px; border-radius: 5px; margin: 20px;'>";
        echo "<strong>⚠ Already Exists!</strong> Pakistan contract (PAK-001) already exists in database.";
        echo "</div>";
        $conn->close();
        exit;
    }

    $now = date('Y-m-d H:i:s');
    $today = date('Y-m-d');

    // Professional Pakistan-based contract descriptions
    $contractDescription = "SYSTEM SUBSCRIPTION CONTRACT

Type: Monthly Subscription Agreement
Valid From: " . $today . "

This contract outlines the terms and conditions for the use of the Inventory Management System (IMS) on a monthly subscription basis. The subscription charges cover system access, data storage, technical support, and regular maintenance updates as per the agreed schedule.

Monthly Subscription Fee: PKR 5,000 (Five Thousand Rupees Only)
Payment Due Date: 1st of every month
Grace Period: 15 days (until 15th of the month)

The system will remain fully operational during normal business hours (9:00 AM to 6:00 PM PST) with scheduled maintenance windows on alternate Sundays from 11:00 PM to 1:00 AM.";

    $policyDescription = "PAYMENT POLICY & TERMS

1. PAYMENT TERMS
   • Monthly subscription charges are due on or before the 1st day of each month
   • Payment currency: Pakistani Rupees (PKR)
   • Standard billing cycle: 30 days per invoice

2. ACCEPTED PAYMENT METHODS
   • Bank Transfer/Online Fund Transfer (within Pakistan)
   • Cheque (crossed cheque to be sent to registered office)
   • Bank Draft
   • Cash deposit to designated account
   • Jazz Cash / Easypaisa (for amounts below PKR 50,000)
   • HBL PayWave / UBL Omni (for online payments)

3. GRACE PERIOD
   • 15 days extension period is provided beyond the due date (until 15th of month)
   • No system suspension during grace period
   • Late payment may incur 2% additional charges after grace period expires

4. SERVICE SUSPENSION POLICY
   • If payment is not received within the grace period (after 15th of month):
     - System access will be restricted for all regular users
     - Only Super Administrator will retain full system access
     - All other users will be locked out until payment is verified
     - Dashboard will display pending payment notifications

5. PAYMENT VERIFICATION PROCESS
   • Users can upload payment proof documents through the system
   • Accepted proof formats: Bank confirmation, transaction receipt, cheque image, payment slip
   • Proof is verified by Super Administrator within 24 business hours
   • Once verified, system access is immediately restored for all users

6. INVOICE GENERATION
   • Monthly invoices are automatically generated by the system
   • Invoices can be downloaded in PDF format from Payment Management dashboard
   • Each invoice includes GST (if applicable) calculated at 17% on the base amount
   • Invoices are valid receipts for accounting and audit purposes

7. REFUND POLICY
   • No refunds for partial months - subscription charges are for full calendar month
   • Unused days at the end of subscription are non-refundable
   • System termination requires written notice 30 days in advance
   • Advance payments are adjustable against future invoices

8. RENEWAL & DISCONTINUATION
   • Automatic monthly renewal unless cancelled in writing
   • Cancellation must be submitted by the 20th of the current billing month
   • Data will be retained for 30 days after subscription expiry
   • Extended data retention beyond 30 days may incur storage charges

9. SUPPORT & MAINTENANCE
   • Technical support available during business hours (9 AM - 6 PM, Monday-Friday)
   • Non-critical issues: 2-3 business days response time
   • Critical issues: Same business day response (within 4 hours)
   • System updates and patches deployed with advance notice
   • Scheduled maintenance: Alternate Sundays 11 PM - 1 AM (no system access)

10. COMPLIANCE & REGULATIONS
    • System operates in compliance with Data Protection Act, 2018
    • User data is stored on secure servers with AES-256 encryption
    • Regular backups maintained for data recovery purposes
    • PTA compliance for financial transaction logging maintained
    • GST registration and compliance as per FBR regulations

11. DISPUTE RESOLUTION
    • All disputes shall be subject to jurisdiction of courts in Islamabad
    • First resolution attempt through amicable negotiation
    • Escalation to legal proceedings only if negotiation fails
    • Both parties agree to attempt mediation before litigation";

    $contractorInfo = "SYSTEM PROVIDER & SUPPORT

Provider: Inventory Management System Team
Registration: Government of Pakistan - Business Registration

PRIMARY CONTACT
Email: support@inventorysystem.pk
Phone: +92-300-1234567
WhatsApp: +92-300-1234567
Office Hours: 9:00 AM - 6:00 PM (Monday-Friday, PST)

MAILING ADDRESS
Inventory Management Solutions (Pvt) Ltd
Tech Park, Sector I-8/2
Islamabad, Pakistan 44000

PAYMENT DETAILS
Bank Account Name: Inventory Management Solutions (Pvt) Ltd
Bank Name: Habib Bank Limited (HBL)
Account Number: XX-XXXX-XXXX-XXXX
IBAN: PK36HBLC0001234567890123
Branch: Blue Area, Islamabad

For Jazz Cash / Easypaisa:
Mobile Number: 03001234567 (Registered as Inventory Systems)

All payments should include invoice number or contract reference in the remarks/memo field for quick reconciliation.";

    $fullDescription = "INVENTORY MANAGEMENT SYSTEM - PROFESSIONAL SUBSCRIPTION AGREEMENT

This is a comprehensive service agreement for the use of the Inventory Management System, a cloud-based inventory tracking and management solution designed for businesses operating in Pakistan. The system provides real-time inventory monitoring, automated invoicing, multi-warehouse management, and detailed financial reporting capabilities.

The subscription is billed on a monthly basis at PKR 5,000 per month with a mandatory 15-day grace period for payment processing. All invoices include applicable GST at current rates and are issued automatically on the first day of each billing cycle.

The system adheres to Pakistani regulatory standards including GST compliance (FBR), data protection laws, and PTA regulations for financial transactions. Regular automatic backups ensure business continuity, and 24-hour support is available for critical issues.

Users have full access to all features including unlimited invoice creation, multi-user accounts, real-time reporting, and API integrations. Payment proofs can be uploaded directly through the system for quick verification by administrators, ensuring minimal system downtime.

This agreement remains valid for the duration of the subscription and auto-renews monthly unless cancelled with 30 days written notice. All terms and conditions are subject to Pakistani law and the jurisdiction of Islamabad courts.

For inquiries or support, contact the Support Team through the contact details provided in the system's Help section.";

    // Escape strings for SQL
    $contractDescription = $conn->real_escape_string($contractDescription);
    $policyDescription = $conn->real_escape_string($policyDescription);
    $contractorInfo = $conn->real_escape_string($contractorInfo);
    $fullDescription = $conn->real_escape_string($fullDescription);

    // Execute insert statement directly
    $sql = "INSERT INTO system_contracts (
        contract_number,
        contract_name,
        contract_type,
        contractor_name,
        contractor_cnic,
        contractor_phone,
        contractor_email,
        contractor_address,
        installation_date,
        contract_start_date,
        contract_end_date,
        monthly_charges,
        yearly_charges,
        monthly_due_date,
        maximum_extension_days,
        system_status,
        contract_description,
        policy_description,
        contractor_info,
        full_description,
        created_at,
        updated_at,
        created_by,
        updated_by,
        is_active,
        is_deleted
    ) VALUES (
        'PAK-001',
        'Pakistan Professional Subscription - Monthly',
        'monthly',
        'Inventory Management Solutions (Pvt) Ltd',
        '12345-6789012-3',
        '+92-300-1234567',
        'support@inventorysystem.pk',
        'Tech Park, Sector I-8/2, Islamabad, Pakistan 44000',
        '$today',
        '$today',
        NULL,
        5000.00,
        0.00,
        1,
        15,
        'active',
        '$contractDescription',
        '$policyDescription',
        '$contractorInfo',
        '$fullDescription',
        '$now',
        '$now',
        1,
        1,
        1,
        0
    )";

    if ($conn->query($sql) === TRUE) {
        echo "<div style='background-color: #d4edda; color: #155724; padding: 15px; border-radius: 5px; margin: 20px;'>";
        echo "<strong>✓ Success!</strong> Pakistan-based contract has been added successfully.<br>";
        echo "Contract Number: <strong>PAK-001</strong><br>";
        echo "Monthly Charges: <strong>PKR 5,000</strong><br>";
        echo "Status: <strong>Active</strong><br>";
        echo "Created: <strong>" . $now . "</strong>";
        echo "</div>";
    } else {
        echo "<div style='background-color: #f8d7da; color: #721c24; padding: 15px; border-radius: 5px; margin: 20px;'>";
        echo "<strong>✗ Error!</strong> Failed to insert contract: " . $conn->error;
        echo "</div>";
    }

    $conn->close();

} catch (Exception $e) {
    echo "<div style='background-color: #f8d7da; color: #721c24; padding: 15px; border-radius: 5px; margin: 20px;'>";
    echo "<strong>✗ Error!</strong> " . $e->getMessage();
    echo "</div>";
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Add Pakistan Contract</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            border-bottom: 3px solid #007bff;
            padding-bottom: 10px;
        }
        .info {
            background-color: #e7f3ff;
            color: #0066cc;
            padding: 15px;
            border-left: 4px solid #0066cc;
            margin: 20px 0;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🇵🇰 Pakistan Contract Database Initialization</h1>
        <div class="info">
            <strong>Note:</strong> This script adds a professional Pakistan-based contract record to your system database.
            The contract includes realistic Pakistani business details and professional payment policies.
        </div>

        <h3>Contract Details Added:</h3>
        <ul>
            <li><strong>Contract Name:</strong> Pakistan Professional Subscription - Monthly</li>
            <li><strong>Contract Number:</strong> PAK-001</li>
            <li><strong>Monthly Charges:</strong> PKR 5,000</li>
            <li><strong>Payment Due Date:</strong> 1st of every month</li>
            <li><strong>Grace Period:</strong> 15 days</li>
            <li><strong>Provider:</strong> Inventory Management Solutions (Pvt) Ltd</li>
            <li><strong>CNIC Format:</strong> Pakistani format</li>
            <li><strong>Contact Email:</strong> support@inventorysystem.pk</li>
            <li><strong>Contact Phone:</strong> +92-300-1234567</li>
            <li><strong>Office Location:</strong> Tech Park, Sector I-8/2, Islamabad</li>
        </ul>

        <h3>Included Features:</h3>
        <ul>
            <li>✓ Professional contract description with subscription terms</li>
            <li>✓ Comprehensive payment policy (11 sections)</li>
            <li>✓ Pakistani payment methods (Bank Transfer, Cheque, Jazz Cash, Easypaisa, HBL PayWave)</li>
            <li>✓ GST compliance at 17%</li>
            <li>✓ Data Protection Act compliance</li>
            <li>✓ PTA compliance information</li>
            <li>✓ FBR GST registration details</li>
            <li>✓ Support hours and escalation procedures</li>
            <li>✓ Dispute resolution through Islamabad courts</li>
            <li>✓ Complete contractor information with bank details</li>
        </ul>

        <h3>How to Use:</h3>
        <ol>
            <li>Run this script via browser or command line: <code>php ADD_PAKISTAN_CONTRACT.php</code></li>
            <li>Contract will be added to database automatically</li>
            <li>Log in to your system and go to <strong>Settings → System Plan</strong></li>
            <li>View and edit the contract details as needed</li>
            <li>Update any details (email, phone, bank account) specific to your organization</li>
        </ol>

        <div class="info">
            <strong>After Running:</strong> Delete this script (ADD_PAKISTAN_CONTRACT.php) from your server for security purposes.
        </div>
    </div>
</body>
</html>
