#!/bin/bash

##############################################################################
# INVENTORY MANAGEMENT SYSTEM - CRON SETUP SCRIPT
#
# This script configures automated tasks (backups, health checks, log rotation)
# Run as: sudo ./scripts/cron-setup.sh
##############################################################################

set -e

APP_ROOT="/var/www/inventory_system"
CRON_USER="www-data"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "\n${YELLOW}=== CRON SETUP FOR INVENTORY SYSTEM ===${NC}\n"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}This script must be run as root (use sudo)${NC}"
    exit 1
fi

# Make scripts executable
echo -e "${YELLOW}Making scripts executable...${NC}"
chmod +x "$APP_ROOT/scripts/backup-database.sh"
chmod +x "$APP_ROOT/scripts/health-check.sh"
chmod +x "$APP_ROOT/scripts/optimize-production.sh"
echo -e "${GREEN}✓ Scripts are now executable${NC}\n"

# Create cron jobs file
CRON_FILE="/tmp/inventory-cron-$(date +%s)"
cat > "$CRON_FILE" << 'EOF'
# Inventory Management System - Automated Tasks
# Generated by cron-setup.sh

# Database backups - Daily at 2:00 AM
0 2 * * * /var/www/inventory_system/scripts/backup-database.sh >> /var/www/inventory_system/runtime/logs/cron-backup.log 2>&1

# Health checks - Every 30 minutes
*/30 * * * * /var/www/inventory_system/scripts/health-check.sh >> /var/www/inventory_system/runtime/logs/cron-health.log 2>&1

# Clear old logs - Weekly at 3:00 AM on Sunday
0 3 * * 0 find /var/www/inventory_system/runtime/logs -name "*.log" -mtime +30 -delete

# Clear cache - Daily at 1:00 AM
0 1 * * * rm -rf /var/www/inventory_system/runtime/cache/* 2>/dev/null || true

# Optimize assets - Weekly at 4:00 AM on Sunday
0 4 * * 0 rm -rf /var/www/inventory_system/web/assets/* 2>/dev/null || true

# Check disk space - Twice daily (6 AM and 6 PM)
0 6,18 * * * df -h /var/www >> /var/www/inventory_system/runtime/logs/disk-usage.log

EOF

echo -e "${YELLOW}Cron jobs to be added:${NC}\n"
cat "$CRON_FILE" | grep -v "^#" | grep -v "^$"

echo -e "\n${YELLOW}Installing cron jobs for $CRON_USER...${NC}"

# Install cron jobs
crontab -u "$CRON_USER" -l 2>/dev/null > /tmp/cron-existing || true

# Check if cron jobs already exist
if grep -q "inventory_system/scripts/backup-database.sh" /tmp/cron-existing 2>/dev/null; then
    echo -e "${YELLOW}⚠ Cron jobs already configured${NC}"
    echo -e "${YELLOW}Do you want to replace them? (y/n)${NC}"
    read -r response
    if [ "$response" != "y" ]; then
        rm -f "$CRON_FILE"
        exit 0
    fi
    # Remove old entries
    grep -v "inventory_system" /tmp/cron-existing > /tmp/cron-new || true
    cat /tmp/cron-new "$CRON_FILE" | crontab -u "$CRON_USER" -
else
    # Add new entries to existing cron
    cat /tmp/cron-existing "$CRON_FILE" | crontab -u "$CRON_USER" -
fi

echo -e "${GREEN}✓ Cron jobs installed successfully${NC}\n"

# Verify installation
echo -e "${YELLOW}Verifying cron jobs...${NC}\n"
crontab -u "$CRON_USER" -l | grep "inventory_system" | sed 's/^/  /'

# Create log files if they don't exist
echo -e "\n${YELLOW}Creating log files...${NC}"
touch /var/www/inventory_system/runtime/logs/cron-backup.log
touch /var/www/inventory_system/runtime/logs/cron-health.log
touch /var/www/inventory_system/runtime/logs/disk-usage.log
chown "$CRON_USER:$CRON_USER" /var/www/inventory_system/runtime/logs/cron-*.log
chmod 644 /var/www/inventory_system/runtime/logs/cron-*.log
echo -e "${GREEN}✓ Log files created${NC}\n"

# Cleanup
rm -f "$CRON_FILE" /tmp/cron-existing /tmp/cron-new

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}✓ CRON SETUP COMPLETED${NC}"
echo -e "${GREEN}========================================${NC}\n"

echo -e "${YELLOW}Configured Tasks:${NC}"
echo "  1. Database backups - Daily at 2:00 AM"
echo "  2. Health checks - Every 30 minutes"
echo "  3. Log cleanup - Weekly (logs > 30 days old)"
echo "  4. Cache cleanup - Daily at 1:00 AM"
echo "  5. Asset cleanup - Weekly at 4:00 AM"
echo "  6. Disk space monitoring - At 6 AM & 6 PM"
echo ""

echo -e "${YELLOW}Log files:${NC}"
echo "  • Backup logs: /var/www/inventory_system/runtime/logs/cron-backup.log"
echo "  • Health logs: /var/www/inventory_system/runtime/logs/cron-health.log"
echo "  • Disk usage: /var/www/inventory_system/runtime/logs/disk-usage.log"
echo ""

echo -e "${YELLOW}View cron jobs with:${NC}"
echo "  crontab -u $CRON_USER -l"
echo ""

echo -e "${YELLOW}Edit cron jobs with:${NC}"
echo "  crontab -u $CRON_USER -e"
echo ""

echo -e "${GREEN}Setup complete! Your system is now configured for automated maintenance.${NC}\n"

exit 0
